apiVersion: v2
name: telemongo
description: A basic Teleport deployment
kind: Service

version: 0.1.0

appVersion: "1.16.0"
spec:
  type: ExternalName
  externalName: telemongo.default.svc.cluster.local


dependencies:
- name: teleport-cluster
  version: "11.0.1"
  repository: "https://charts.releases.teleport.dev"
#- name: mongodb
#  version: "13.4.1"
#  repository: "https://charts.bitnami.com/bitnami"
